FROM nvidia/cuda:12.4.1-devel-ubuntu22.04 as builder

# FIXME: should be able to find this dynamically
ARG GPU_ARCH=89

# GPU_ARCH and USEGPU environment variable used by build_proc.sh
ENV FFTW_LIB=/usr/lib/x86_64-linux-gnu/libfftw3f.a
ENV GPU_ARCH=${GPU_ARCH}
ENV USEGPU=true
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends unzip vim curl git build-essential gfortran libfftw3-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY . /srg/
COPY ./scripts/build_proc.sh /srg/
RUN cd /srg && ./build_proc.sh && cd /

FROM nvidia/cuda:12.4.1-runtime-ubuntu22.04 as runner

# For opencontainers label definitions, see:
#    https://github.com/opencontainers/image-spec/blob/master/annotations.md
LABEL org.opencontainers.image.title="SRG"
LABEL org.opencontainers.image.description="HyP3 plugin for Stanford Radar Group Processor SAR processing"
LABEL org.opencontainers.image.vendor="Alaska Satellite Facility"
LABEL org.opencontainers.image.authors="ASF Tools Team <UAF-asf-apd@alaska.edu>"
LABEL org.opencontainers.image.licenses="BSD-3-Clause"
LABEL org.opencontainers.image.url="https://github.com/ASFHyP3/srg"
LABEL org.opencontainers.image.source="https://github.com/ASFHyP3/srg"
LABEL org.opencontainers.image.documentation="https://hyp3-docs.asf.alaska.edu"

ARG CONDA_UID=1000
ARG CONDA_GID=1000
ARG MINIFORGE_NAME=Miniforge3
ARG MINIFORGE_VERSION=24.3.0-0

ENV CONDA_DIR=/opt/conda
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH=${CONDA_DIR}/bin:${PATH}
ENV PYTHONDONTWRITEBYTECODE=true
ENV PROC_HOME=/srg
ENV MYHOME=/home/conda
ENV DEBIAN_FRONTEND=noninteractive

# Conda setup
RUN apt-get update && apt-get install --no-install-recommends --yes wget bzip2 ca-certificates git > /dev/null && \
    wget --no-hsts --quiet https://github.com/conda-forge/miniforge/releases/download/${MINIFORGE_VERSION}/${MINIFORGE_NAME}-${MINIFORGE_VERSION}-Linux-$(uname -m).sh -O /tmp/miniforge.sh && \
    /bin/bash /tmp/miniforge.sh -b -p ${CONDA_DIR} && \
    rm /tmp/miniforge.sh && \
    conda clean --tarballs --index-cache --packages --yes && \
    find ${CONDA_DIR} -follow -type f -name '*.a' -delete && \
    find ${CONDA_DIR} -follow -type f -name '*.pyc' -delete && \
    conda clean --force-pkgs-dirs --all --yes  && \
    echo ". ${CONDA_DIR}/etc/profile.d/conda.sh && conda activate base" >> /etc/skel/.bashrc && \
    echo ". ${CONDA_DIR}/etc/profile.d/conda.sh && conda activate base" >> ~/.bashrc

RUN apt-get install -y --no-install-recommends unzip vim curl gfortran && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN groupadd -g "${CONDA_GID}" --system conda && \
    useradd -l -u "${CONDA_UID}" -g "${CONDA_GID}" --system -d /home/conda -m  -s /bin/bash conda && \
    chown -R conda:conda /opt && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> /home/conda/.profile && \
    echo "conda activate base" >> /home/conda/.profile

SHELL ["/bin/bash", "-l", "-c"]

USER ${CONDA_UID}
WORKDIR /home/conda/

COPY --chown=${CONDA_UID}:${CONDA_GID} --from=builder /srg/snaphu_v2.0b0.0.0/bin/snaphu /srg/bin/snaphu
COPY --chown=${CONDA_UID}:${CONDA_GID} --from=builder /srg /srg

RUN mamba env create -f /srg/environment.yml && \
    conda clean -afy && \
    conda activate srg && \
    sed -i 's/conda activate base/conda activate srg/g' /home/conda/.profile && \
    python -m pip install --no-cache-dir /srg

ENTRYPOINT ["/srg/src/srg/etc/entrypoint.sh"]
CMD ["-h"]
